#!/bin/bash

run() {
    echo "RUNNING: '${1}' ..."
    ${1}
    exit_code=$?
    if [[ ${exit_code} != 0 ]]; then
        >&2 echo "command '${1}' failed with exit code '${exit_code}'"
        exit 2
    fi
}

process=${PROCESS}
branch=${BRANCH}
repo=${SKYUPD_REPO}
args=$(eval echo $@)
bin_dir="${GOBIN}"

orig_branch=$(git rev-parse --abbrev-ref HEAD)
temp_branch="temp/${BRANCH}"

echo "## UPDATING REPOSITORY ##"

run "go get -d -u ${repo}"
run "git fetch --all --prune"
run "git checkout ${BRANCH} -b ${temp_branch}"

echo "## CHECKING IF CURRENT BINARY IS LATEST ##"

run "cd ${GOPATH}/src/${repo}/cmd/${process}"
run "go build ${args}"

orig_file="${bin_dir}/${process}"
new_file="./${process}"

echo "Checking if '${orig_file}' and '${new_file}' differ ..."

if diff ${orig_file} ${new_file} > /dev/null 2>&1; then
    echo "No update found."
    final_code=1
else
    echo "Update found."
    final_code=0
fi

echo "## CLEANING UP ##"

run "rm -f ${new_file}"
run "cd ${GOPATH}/src/${repo}"
run "git checkout ${orig_branch}"
run "git branch -D ${temp_branch}"

exit ${final_code}