#!/bin/bash

run() {
    echo "RUNNING: '${1}' ..."
    ${1}
    exit_code=$?
    if [[ ${exit_code} != 0 ]]; then
        >&2 echo "command '${1}' failed with exit code '${exit_code}'"
        exit 2
    fi
}

repo=${SKYUPD_REPO}
to_version=${SKYUPD_TO_VERSION}
args=$(eval echo ${$@})

echo "## UPDATING ##"

run "go get -d -u ${repo}"
run "cd ${GOPATH}/src/${repo}"

orig_branch=$(git rev-parse --abbrev-ref HEAD)
temp_branch="temp/${BRANCH}"

run "git fetch --all --tags --prune"
run "git checkout tags/${to_version} -b ${temp_branch}"

run "go install ./..."

echo "## CLEANING UP ##"

run "git checkout ${orig_branch}"
run "git branch -D ${temp_branch}"

echo "done."
exit 0