#!/bin/bash

run() {
    echo "RUNNING: '${1}' ..."
    ${1}
    exit_code=$?
    if [[ ${exit_code} != 0 ]]; then
        >&2 echo "command '${1}' failed with exit code '${exit_code}'"
        exit 2
    fi
}

repo=${SKYUPD_REPO}
args=$(eval echo ${$@})

echo "## UPDATING ##"

run "go get -d -u ${repo}"
run "cd ${GOPATH}/src/${repo}/cmd"
run "go install ./..."

echo "## TODO: COPY APPS TO APPS DIR ##"
